# SPDX-许可证标识符: (GPL-2.0-only 或 BSD-2-Clause)
%YAML 1.2
---
$id: http://devicetree.org/schemas/fpga/lattice,sysconfig.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

标题: Lattice Slave SPI sysCONFIG FPGA 管理器

维护者:
  - 弗拉基米尔·格奥尔吉耶夫 <v.georgiev@metrotek.ru>

描述: |
  Lattice 的 sysCONFIG 接口，主要用于 FPGA 配置等目的，具有 Slave 串行外设接口。仅支持全配置。
  对 ECP5 的编程是通过将未压缩的位流图像（.bit 格式）写入到 FPGA 的 SRAM 配置内存中完成的。
属性:
  compatible:
    枚举:
      - lattice,sysconfig-ecp5

  reg:
    最大项数: 1

  program-gpios:
    描述:
      连接到设备上 PROGRAMN（低电平有效）引脚的一个 GPIO 线
启动配置序列
最大项数: 1

  init-gpios:
    描述:
      连接到设备上 INITN（低电平有效）引脚的一个 GPIO 线
指示 FPGA 已准备好进行配置
最大项数: 1

  done-gpios:
    描述:
      连接到设备上 DONE（高电平有效）引脚的一个 GPIO 线
指示配置序列已完成
最大项数: 1

必需:
  - compatible
  - reg

allOf:
  - $ref: /schemas/spi/spi-peripheral-props.yaml

  - 如果:
      属性:
        compatible:
          包含:
            常量: lattice,sysconfig-ecp5
    则:
      属性:
        spi-max-frequency:
          最大值: 60000000

未评估属性: false

示例:
  - |
    #include <dt-bindings/gpio/gpio.h>

    spi {
        #address-cells = <1>;
        #size-cells = <0>;

        fpga-mgr@0 {
            compatible = "lattice,sysconfig-ecp5";
            reg = <0>;
            spi-max-frequency = <20000000>;
            program-gpios = <&gpio3 4 GPIO_ACTIVE_LOW>;
            init-gpios = <&gpio3 3 GPIO_ACTIVE_LOW>;
            done-gpios = <&gpio3 2 GPIO_ACTIVE_HIGH>;
        };
    };
