#!/bin/bash

messages=("$@")
content=""
for message in "${messages[@]}";do
	content+="$message "
	#echo "$message"
done
#echo "$content"

echo "Question:" >> ~/his
echo "$content" >> ~/his

#exit
echo "--------------------------------------------"
echo "--------------------------------------------" >> ~/his
echo "Answer:" >> ~/his

curl -s --location 'https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation' --header "Authorization: Bearer $OPENAI_API_KEY" --header 'Content-Type:application/json' --data '{
	"model": "qwen-turbo-0624",
	"input": {
		"messages":[
			{
				"role":"system",
				"content":"you are a helpful assistant"
			},
			{
				"role":"user",
				"content":"'"$content"'"
			}
		]
	},
	"parameters":{
		"result_format":"message"
	}

}' | jq -M -r '.output.choices[0].message.content' > ~/tmp
cat ~/tmp
cat ~/tmp >> ~/his

echo ""
echo "--------------------------------------------"
echo "--------------------------------------------" >> ~/his

#echo "输入内容：$1"

#jq -M 没有颜色，默认绿色   -r格式化
#curl -s 无管道流
