# SPDX-许可证标识符: (GPL-2.0 或 BSD-2-Clause)
%YAML 1.2
---
$id: http://devicetree.org/schemas/soc/xilinx/xlnx,vcu-settings.yaml#
$schema: http://devicetree.org/meta-schemas/core.yaml#

标题: Xilinx VCU 设置

维护者:
  - Michael Tretter <kernel@pengutronix.de>

描述: |
  Xilinx VCU 设置提供了关于视频编解码器单元配置的信息。
属性:
  compatible:
    项目:
      - 常量: xlnx,vcu-settings
      - 常量: syscon

  reg:
    最大项数: 1

必需:
  - compatible
  - reg

额外属性: false

示例:
  - |
    fpga {
        #address-cells = <2>;
        #size-cells = <2>;

        xlnx_vcu: vcu@a0041000 {
            compatible = "xlnx,vcu-settings", "syscon";
            reg = <0x0 0xa0041000 0x0 0x1000>;
        };
    };
